### ISSUE TITLE
Installation on windows failing

### ISSUE THREAD

**Issue by Slind14** [JamesMGreene/node-partty#2]
Hey,

I tried to install it on a win 7 64bit machine but it always ends up with:

```
\
> partty@0.5.4 preinstall C:\Users\Slind\Documents\test\node_modules\cloudcmd\node_modules\partty
> ( node -e 'process.exit(process.platform === "win32" ? 0 : 1);' && git submodule update --init --recursive ) || echo '
Submodule is not required as you are not running on Windows!'

' was unexpected at this time.

npm ERR! partty@0.5.4 preinstall: `( node -e 'process.exit(process.platform === "win32" ? 0 : 1);' && git submodule upda
te --init --recursive ) || echo 'Submodule is not required as you are not running on Windows!'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the partty@0.5.4 preinstall script.
npm ERR! This is most likely a problem with the partty package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ( node -e 'process.exit(process.platform === "win32" ? 0 : 1);' && git submodule update --init --recursive
) || echo 'Submodule is not required as you are not running on Windows!'
npm ERR! You can get their info via:
npm ERR!     npm owner ls partty
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js"
 "i" "partty"
npm ERR! cwd C:\Users\Slind\Documents\test\node_modules\cloudcmd
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

**Comment by JamesMGreene** [comment]
That's weird. What does running the following output for you?

``` shell
node -e "console.log(process.platform);"
```

A value of `"win64"` wouldn't be shocking, though everything I've read suggests it should still be  reporting`"win32"`.

Also, what terminal program are you using? Command Prompt, PowerShell, Cygwin, MinGW32, MSysGit, etc.?

**Comment by JamesMGreene** [comment]
Oh, also: do you have `git` installed and configured?

**Comment by JamesMGreene** [comment]
Oh, I bet it also needs to run `git init` first since you're installing from NPM.

**Comment by Slind14** [comment]
1. it reports `win32`, Command Prompt
2. yes, I have for the win console (not only bash)
3. I can run git init just fine

Do I need to do something else besides `git clone https://github.com/JamesMGreene/node-partty.git` & `npm install` or `npm install partty`?

**Comment by JamesMGreene** [comment]
I believe the former combo should work until i get this patched. Does it not?

``` shell
:: From project dir
cd node_modules
git clone https://github.com/JamesMGreene/node-partty.git partty
cd partty
npm install
```

Note that if you run a subsequent `npm install` at your project dir level, it may overwrite/mess-up this hacked install. :confused:

**Comment by JamesMGreene** [comment]
Can you try the new version `0.5.5`?

**Comment by JamesMGreene** [comment]
(Hopefully fixed by 327a506291bed121d9e7c339f5b419ca8ac1d051)

**Comment by Slind14** [comment]
Unfortunately it didn't work:

```
C:\Users\Slind\Documents\test>git clone https://github.com/JamesMGreene/node-par
tty.git partty
Cloning into 'partty'...
remote: Counting objects: 1281, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 1281 (delta 0), reused 0 (delta 0), pack-reused 1275
Receiving objects: 100% (1281/1281), 302.26 KiB | 0 bytes/s, done.
Resolving deltas: 100% (557/557), done.
Checking connectivity... done.

C:\Users\Slind\Documents\test>cd partty

C:\Users\Slind\Documents\test\partty>npm install

> partty@0.5.5 preinstall C:\Users\Slind\Documents\test\partty
> ( node -e 'process.exit(process.platform === "win32" ? 0 : 1);' && (pushd .git
 2>NUL && popd || git init) && git submodule update --init --recursive ) || echo
 'Submodule is not required as you are not running on Windows!'

' was unexpected at this time.

npm ERR! partty@0.5.5 preinstall: `( node -e 'process.exit(process.platform ===
"win32" ? 0 : 1);' && (pushd .git 2>NUL && popd || git init) && git submodule up
date --init --recursive ) || echo 'Submodule is not required as you are not runn
ing on Windows!'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the partty@0.5.5 preinstall script.
npm ERR! This is most likely a problem with the partty package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ( node -e 'process.exit(process.platform === "win32" ? 0 : 1);' &&
(pushd .git 2>NUL && popd || git init) && git submodule update --init --recursiv
e ) || echo 'Submodule is not required as you are not running on Windows!'
npm ERR! You can get their info via:
npm ERR!     npm owner ls partty
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\Users\Slind\Documents\test\partty
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\Slind\Documents\test\partty\npm-debug.log
npm ERR! not ok code 0
```

**Comment by JamesMGreene** [comment]
Try deleting the whole "partty" directory and then do `npm install --save partty@0.5.5`.

**Comment by Slind14** [comment]
:(

```
C:\Users\Slind\Documents\test>npm install --save partty@0.5.5
-
> partty@0.5.5 preinstall C:\Users\Slind\Documents\test\node_modules\partty
> ( node -e 'process.exit(process.platform === "win32" ? 0 : 1);' && (pushd .git 2>NUL && popd || git init) && git submo
dule update --init --recursive ) || echo 'Submodule is not required as you are not running on Windows!'

' was unexpected at this time.

npm ERR! partty@0.5.5 preinstall: `( node -e 'process.exit(process.platform === "win32" ? 0 : 1);' && (pushd .git 2>NUL
&& popd || git init) && git submodule update --init --recursive ) || echo 'Submodule is not required as you are not runn
ing on Windows!'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the partty@0.5.5 preinstall script.
npm ERR! This is most likely a problem with the partty package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ( node -e 'process.exit(process.platform === "win32" ? 0 : 1);' && (pushd .git 2>NUL && popd || git init) &
& git submodule update --init --recursive ) || echo 'Submodule is not required as you are not running on Windows!'
npm ERR! You can get their info via:
npm ERR!     npm owner ls partty
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js"
 "install" "--save" "partty@0.5.5"
npm ERR! cwd C:\Users\Slind\Documents\test
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

**Comment by JamesMGreene** [comment]
Updated again. Could you try deleting the whole "partty" directory and then do `npm install --save partty@0.5.6`?

**Comment by JamesMGreene** [comment]
Just tried this out on my own Windows box.  For me, I saw the same installation errors for `v0.5.5` as you reported.  Installing `v0.5.6` went much better (got past the previous error, anyway) but, for me, failed thereafter on a msbuild/machine setup/configuration discrepancy:

```
gyp info spawn C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
Build started 7/10/2015 12:47:15 AM.
Project "d:\Development\Personal\testtesttest\node_modules\partty\build\binding
.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Release|x64".
Project "d:\Development\Personal\testtesttest\node_modules\partty\build\binding
.sln" (1) is building "d:\Development\Personal\testtesttest\node_modules\partty
\build\pty.vcxproj.metaproj" (2) on node 1 (default targets).
Project "d:\Development\Personal\testtesttest\node_modules\partty\build\pty.vcx
proj.metaproj" (2) is building "d:\Development\Personal\testtesttest\node_modul
es\partty\build\deps\winpty\winpty-agent.vcxproj" (3) on node 1 (default target
s).
d:\Development\Personal\testtesttest\node_modules\partty\build\deps\winpty\winp
ty-agent.vcxproj(18,3): error MSB4019: The imported project "d:\Microsoft.Cpp.D
efault.props" was not found. Confirm that the path in the <Import> declaration
is correct, and that the file exists on disk.
Done Building Project "d:\Development\Personal\testtesttest\node_modules\partty
\build\deps\winpty\winpty-agent.vcxproj" (default targets) -- FAILED.

Project "d:\Development\Personal\testtesttest\node_modules\partty\build\pty.vcx
proj.metaproj" (2) is building "d:\Development\Personal\testtesttest\node_modul
es\partty\build\deps\winpty\winpty.vcxproj" (4) on node 1 (default targets).
d:\Development\Personal\testtesttest\node_modules\partty\build\deps\winpty\winp
ty.vcxproj(18,3): error MSB4019: The imported project "d:\Microsoft.Cpp.Default
.props" was not found. Confirm that the path in the <Import> declaration is cor
rect, and that the file exists on disk.
Done Building Project "d:\Development\Personal\testtesttest\node_modules\partty
\build\deps\winpty\winpty.vcxproj" (default targets) -- FAILED.

Done Building Project "d:\Development\Personal\testtesttest\node_modules\partty
\build\pty.vcxproj.metaproj" (default targets) -- FAILED.

Done Building Project "d:\Development\Personal\testtesttest\node_modules\partty
\build\binding.sln" (default targets) -- FAILED.


Build FAILED.

"d:\Development\Personal\testtesttest\node_modules\partty\build\binding.sln" (d
efault target) (1) ->
"d:\Development\Personal\testtesttest\node_modules\partty\build\pty.vcxproj.met
aproj" (default target) (2) ->
"d:\Development\Personal\testtesttest\node_modules\partty\build\deps\winpty\win
pty-agent.vcxproj" (default target) (3) ->
  d:\Development\Personal\testtesttest\node_modules\partty\build\deps\winpty\wi
npty-agent.vcxproj(18,3): error MSB4019: The imported project "d:\Microsoft.Cpp
.Default.props" was not found. Confirm that the path in the <Import> declaratio
n is correct, and that the file exists on disk.


"d:\Development\Personal\testtesttest\node_modules\partty\build\binding.sln" (d
efault target) (1) ->
"d:\Development\Personal\testtesttest\node_modules\partty\build\pty.vcxproj.met
aproj" (default target) (2) ->
"d:\Development\Personal\testtesttest\node_modules\partty\build\deps\winpty\win
pty.vcxproj" (default target) (4) ->
  d:\Development\Personal\testtesttest\node_modules\partty\build\deps\winpty\wi
npty.vcxproj(18,3): error MSB4019: The imported project "d:\Microsoft.Cpp.Defau
lt.props" was not found. Confirm that the path in the <Import> declaration is c
orrect, and that the file exists on disk.

    0 Warning(s)
    2 Error(s)

Time Elapsed 00:00:02.79
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\Program Files (x86)\nodejs\node_mo
dules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:
12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "c:\\Program Files (x86)\\nodejs\\node_modules\\npm\\nod
e_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd d:\Development\Personal\testtesttest\node_modules\partty
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
npm verb unsafe-perm in lifecycle true
npm info partty@0.5.6 Failed to exec install script
npm info d:\Development\Personal\testtesttest\node_modules\partty unbuild
npm info preuninstall partty@0.5.6
npm info uninstall partty@0.5.6
npm verb true,d:\Development\Personal\testtesttest\node_modules,d:\Development\P
ersonal\testtesttest\node_modules unbuild partty@0.5.6
npm info postuninstall partty@0.5.6
npm ERR! partty@0.5.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the partty@0.5.6 install script.
npm ERR! This is most likely a problem with the partty package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls partty
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Program Files (x86)\\nodejs\\node.exe" "c:\\Program Files
(x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "partty@0.
5.6"
npm ERR! cwd d:\Development\Personal\testtesttest
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! code ELIFECYCLE
npm verb exit [ 1, true ]
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     d:\Development\Personal\testtesttest\npm-debug.log
npm ERR! not ok code 0

``
```

**Comment by JamesMGreene** [comment]
Pulling out the actual failure to highlight it:

```
d:\Development\Personal\testtesttest\node_modules\partty\build\deps\winpty\
winpty.vcxproj(18,3): error MSB4019: The imported project
"d:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in
the <Import> declaration is correct, and that the file exists on disk.
```

**Comment by Slind14** [comment]
hmm, I end up with a MSBUILD error, even after installing .NET Framework 2.0 SDK:

```
C:\Users\Slind\Documents\test>npm install --save partty@0.5.6
/
> partty@0.5.6 preinstall C:\Users\Slind\Documents\test\node_modules\partty
> ( node -e "process.exit(process.platform === 'win32' ? 0 : 1);" && (pushd .git 2>NUL && popd || git init) && git submo
dule update --init --recursive ) || echo "Submodule is not required as you are not running on Windows."

Initialized empty Git repository in C:/Users/Slind/Documents/test/node_modules/partty/.git/

> partty@0.5.6 install C:\Users\Slind\Documents\test\node_modules\partty
> node-gyp rebuild


C:\Users\Slind\Documents\test\node_modules\partty>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..
\node_modules\node-gyp\bin\node-gyp.js" rebuild
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framew
ork 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it i
s installed elsewhere.  [C:\Users\Slind\Documents\test\node_modules\partty\build\binding.sln]
MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framew
ork 2.0 SDK, 2) install Microsoft Visual Studio 2005 or 3) add the location of the component to the system path if it i
s installed elsewhere.  [C:\Users\Slind\Documents\test\node_modules\partty\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:2
67:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuil
d"
gyp ERR! cwd C:\Users\Slind\Documents\test\node_modules\partty
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! partty@0.5.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the partty@0.5.6 install script.
npm ERR! This is most likely a problem with the partty package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls partty
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js"
 "install" "--save" "partty@0.5.6"
npm ERR! cwd C:\Users\Slind\Documents\test
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

**Comment by JamesMGreene** [comment]
Maybe you _also_ need to add VCBuild parent directory to your `PATH` variable (option (3) on the error message)...?  Doesn't seem like you should have to but that would be my best/first guess.

**Comment by JamesMGreene** [comment]
BTW, here are the actual supposed build dependencies for the downstream winpty dependency (submodule):  https://github.com/peters/winpty#prerequisites

Pretty sure you should be able to build it without those, theoretically, though... but apparently it didn't work for me! :confounded:

**Comment by Slind14** [comment]
I'm sorry for all the trouble I caused. It is getting far more complicated than I thought and with some changes not worth it for me anymore. I was hoping to see it being used within cloud commander as its current console implementation is super limited.
